### ISSUE TITLE
Updating content

### ISSUE THREAD

**Issue by kiranvaidhya** [xinario/awesome-gan-for-medical-imaging#12]
Hi @xinario,

Nice work! Do you have a tracker to update content? Maybe you should add papers referenced in the Google AI [blog](https://ai.googleblog.com/2020/02/generating-diverse-synthetic-medical.html).

**Comment by xinario** [comment]
Thank you @kiranvaidhya and sorry for the extremely late reply. All the papers currently are added manually. And it's starting to become very hard to maintain now cause the number of papers is increasing drastically. I tried to wrote a bot to automatically query from google scholar but got banned several times so I gave up. 

If you have a better idea of how to implement this tracker idea, feel free to let me know. Also feel free to submit PR to add any missing papers you find of good quality. For now, I'm gonna just close this issue.
